name: Dart realtime application
description: Creating a realtime application with Dart.
version: 0.1.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
